[0D]
op_code = ["str", 7, 2]
name = ["str-json", "QNN"]
description = ["str-json", "Query nodes"]

[53]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
name = ["str-json", "NNLRN"]
description = ["str-json", "Set node into learn mode"]

[54]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
name = ["str-json", "NNULN"]
description = ["str-json", "Release node from learn mode"]

[56]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
name = ["str-json", "NNEVN"]
description = ["str-json", "Request Number of Available Events"]

[57]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
name = ["str-json", "NERD"]
description = ["str-json", "Request to read all available Events"]

[58]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
name = ["str-json", "RQEVN"]
description = ["str-json", "Request Number of Stored Events"]

[6F]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
error_number = ["int", 13, 2]
name = ["str-json", "CMDERR"]
description = ["str-json", "Error message from node in configuration"]

[70]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
number_of_available_events = ["int", 13, 2]
name = ["str-json", "EVNLF"]
description = ["str-json", "Number of Available Events."]

[71]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
node_variable_index = ["int", 13, 2]
name = ["str-json", "NVRD"]
description = ["str-json", "Request read of Node Variable."]

[73]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
parameter_number = ["int", 13, 2]
name = ["str-json", "RQNPN"]
description = ["str-json", "Request Node Parameter"]

[76]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
mode = ["int", 13, 2]
name = ["str-json", "MODE"]
description = ["str-json", "Request a change to module operating mode"]

[78]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
service_index = ["int", 13, 2]
name = ["str-json", "RQSD"]
description = ["str-json", "Request Service Discovery"]

[74]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
number_of_stored_events = ["int", 13, 2]
name = ["str-json", "NUMEV"]
description = ["str-json", "Response to a Request Number of Stored Events"]

[90]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]
event_type = ["str-json", "long"]
name = ["str-json", "ACON"]
description = ["str-json", "On Event"]

[91]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]
event_type = ["str-json", "long"]
name = ["str-json", "ASON"]
description = ["str-json", "Off Event"]

[97]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
node_variable_index = ["int", 13, 2]
node_variable_value = ["int", 15, 2]
name = ["str-json", "NVANS"]
description = ["str-json", "Response to request for node variable value"]

[98]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
device_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]
event_type = ["str-json", "short"]
name = ["str-json", "ASON"]
description = ["str-json", "Short On Event"]

[99]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
device_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]
event_type = ["str-json", "short"]
name = ["str-json", "ASOF"]
description = ["str-json", "Short Off Event"]

[9B]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
parameter_number = ["int", 13, 2]
parameter_value = ['int', 15 , 2]
name = ["str-json", "PARAN"]
description = ["str-json", "Parameter Value"]

[9C]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_id = ["int", 13, 2]
event_variable_id = ["int", 13, 2]
name = ["str-json", "REVAL"]
description = ["str-json", "Request for read of event variables"]

[AC]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
service_index = ["int", 13, 2]
service_type = ["int", 15, 2]
version = ["int", 17, 2]
name = ["str-json", "ESD"]
description = ["str-json", "Extended Service Discovery Response"]

[B2]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_variable_id = ["int", 15, 2]
name = ["str-json", "REQEV"]
description = ["str-json", "Request event variable in learn mode"]

[B5]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_index = ["int", 13, 2]
event_variable_index = ["int", 15, 2]
event_variable_value = ["int", 17, 2]
name = ["str-json", "NEVAL"]
description = ["str-json", "Response to request to read Event variable value"]

[B6]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
manufacturer_id = ["int", 13, 2]
module_id = ["int", 15, 2]
module_identifier = ["str", 13, 4]
flags = ["str", 17, 2]
name = ["str-json", "PNN"]
description = ["str-json", "Response to QNN"]

[D3]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_variable_id = ["int", 15, 2]
event_variable_value = ["int", 17, 2]
name = ["str-json", "EVANS"]
description = ["str-json", "Response to a request event variable in learn mode"]

[E7]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
service_index = ["int", 13, 2]
service_type = ["int", 15, 2]
data1 = ["int", 17, 2]
data2 = ["int", 19, 2]
data3 = ["int", 21, 2]
name = ["str-json", "ESD"]
description = ["str-json", "Extended Service Discovery Response"]

[F2]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_event_identifier = ["str", 13, 8]
event_node_number = ["int", 13, 4]
event_event_number = ["int", 17, 4]
event_id = ["int", 21, 2]
name = ["str-json", "NUMEV"]
description = ["str-json", "Response to a Request Number of Stored Events"]

