[0D]
op_code = ["str", 7, 2]
name = ["str-json", "QNN"]
description = ["str-json", "Query nodes"]

[B6]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
manufacturer_id = ["int", 13, 2]
module_id = ["int", 15, 2]
flags = ["str", 17, 2]
name = ["str-json", "PNN"]
description = ["str-json", "Response to QNN"]

[90]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]

[91]
op_code = ["str", 7, 2]
node_number = ["int", 9, 4]
event_number = ["int", 13, 4]
event_identifier = ['str-out', 9 , 8]
